package ai.dnai.io.pseudorandomfilegenerator.api.exceptions

class WrongNumberOfOrdersException(message: String) : GeneralCustomException(message) {
}